### ISSUE TITLE
Inconsistencies with pageSize, queryDocuments and QueryAPI

### ISSUE THREAD

**Issue by lith-light-g** [Azure/azure-documentdb-js-server#1]
I recently reached over 100 documents in my collections however I encountered an issue. Newer documents wouldn't be fetched by Stored Procedures.

After investigation I think it's related to the `pageSize` property of the Feed Options.
Consider the following stored procedure scripts:
```javascript
function sqlQueryWithoutContains(ids) {
    __.queryDocuments(__.getSelfLink(), 
    "SELECT * FROM i WHERE i.id = '" + ids[0] + "'", 
    { pageSize: 100 }, 
    function (err, feed, options) {
        __.response.setBody(feed);
    });
}
```
```javascript
function sqlQueryWithContains(ids) {
    __.queryDocuments(__.getSelfLink(),
        "SELECT * FROM i WHERE ARRAY_CONTAINS(" + JSON.stringify(ids) + ", i.id)",
        { pageSize: 100 },
        function (err, feed, options) {
        __.response.setBody(feed);
    });
}
```
```javascript
function parameterizedQueryWithoutContains(ids) {
    __.queryDocuments(__.getSelfLink(), {
        query: "SELECT * FROM i WHERE i.id = @id",
        parameters: [{ name: "@id", value: ids[0] }]
    }, { pageSize: 100 },
    function (err, feed, options) {
        __.response.setBody(feed);
    });
}
```
```javascript
function parameterizedQueryWithContains(ids) {
    __.queryDocuments(__.getSelfLink(), {
        query: "SELECT * FROM i WHERE ARRAY_CONTAINS(@ids, i.id)",
        parameters: [{ name: "@ids", value: ids }]
    }, { pageSize: 100 },
    function (err, feed, options) {
        __.response.setBody(feed);
    });
}
```
```javascript
function queryAPIWithoutContains(ids) {
    __.filter(function (i) {
        return i.id == ids[0];
    }, { pageSize: 100 },
    function (err, feed, options) {
        __.response.setBody(feed);
    });
}
```
```javascript
function queryAPIWithContains(ids) {
    __.filter(function (i) {
        return ids.indexOf(i.id) > -1;
    }, { pageSize: 100 },
    function (err, feed, options) {
        __.response.setBody(feed);
    });
}
```
I would execute each script above with `ids = ["e073396f-c49c-4399-9db5-9992804930fa"]`
For every script involving `queryDocuments()` I'd get the desired item.
However when using `filter()` I wouldn't get it.
If I increase the `pageSize` enough I will get the item with `filter()`

The other thing I have noticed is that the request charge for `queryAPIWithoutContains()` is way higher than the `queryDocuments()` counterparts (~40 vs ~12)
When avoiding ARRAY_CONTAINS in `queryDocuments()` I'm saving ~30 RU however doing the same with `filter()` only saves ~5 RU.

I guess `filter()` iterates through each document until `pageSize` is reached and each iteration uses RU.
But `queryDocuments()` will get my item as long as my `pageSize` value is at least 1 which is the expected behaviour according to the documentation.

**Comment by aliuy** [comment]
**SQL: ARRAY_CONTAINS**

`ARRAY_CONTAINS` is optimized to be used on arrays inside your JSON document, rather than an array coming in from a query parameter.

[Example Query](https://www.documentdb.com/sql/demo#Sandbox?SELECT%20food%0AFROM%20food%0AWHERE%20ARRAY_CONTAINS(food.tags,%20%7B%22name%22:%22babyfood%22%7D)):

```sql
SELECT food
FROM food
WHERE ARRAY_CONTAINS(food.tags, {"name":"babyfood"})
```

Where food.tags is an array:
```js
  {
    "id": "05740",
    "description": "Turkey, thigh, from whole bird, meat only, raw",
    "tags": [
      {
        "name": "turkey"
      },
      {
        "name": "thigh"
      },
      {
        "name": "raw"
      }
    ],
    "version": 1,
    "foodGroup": "Poultry Products",
    "nutrients": [
      {
        "id": "262",
        "description": "Caffeine",
        "nutritionValue": 0,
        "units": "mg"
      },
      {
        "id": "307",
        "description": "Sodium, Na",
        "nutritionValue": 124,
        "units": "mg"
      }
    ]
  }
```

**SQl: IN**

In your example, it is better to use the `IN` keyword.

[Example Query](https://www.documentdb.com/sql/demo#Sandbox?SELECT%20food%20%0AFROM%20food%20%0AWHERE%20food.id%20IN%20(%2205740%22,%20%2207050%22)):

```sql
SELECT food 
FROM food 
WHERE food.id IN ("05740", "07050")
```

Example Stored Procedure:
```js
function(ids) {
  var inParam = JSON.stringify(ids).replace("[", "(").replace("]", ")");

  __.queryDocuments(__.getSelfLink(),
    "SELECT * FROM i WHERE i.id IN " + inParam,
    { pageSize: 100 },
    function(err, feed, options) {
      __.response.setBody(feed);
    });
}
```

**JS Query API: filter**

`queryAPIWithoutContains` should return a result properly. I'd like to look deeper if aren't getting one.

As for `queryAPIWithContains` - I believe the query is behaving as expected. 

The JS Query API is able to optimize the following JavaScript constructs so that the query runs on DocumentDB's indices:
 * Simple operators: = + - * / % | ^ & == != === !=== < > <= >= || && << >> >>>! ~
 * Literals, including the object literal: {}
 * var, return

However, DocumentDB is unable to optimize these JavaScript constructs:
 * Control flow (e.g. if, for, while)
 * Function calls

The method call, indexOf(), will result in scanning through the collection (which is why it get's missed given the page-size), rather than a quick index lookup.

**Query Paging**

Similar to running direct queries; queries in stored procedures are returned in pages.

Here is a thorough code sample demonstrating how to handle query paging, response size limits, and script execution bounds.

```js
function (continuationToken) {
  var query = 'SELECT * FROM root';
  var responseBody = [];
  var responseSize = 0;
  var lastContinuationToken;

  tryQuery(continuationToken);

  function tryQuery(continuationToken) {
    // Tune the pageSize to fit your dataset.
    var requestOptions = {
      continuation: continuationToken,
      pageSize: 1
    };

    var accepted = __.queryDocuments(__.getSelfLink(), query, requestOptions,
      function(err, feed, responseOptions) {
        // The size of the current query response page.
        var queryPageSize = JSON.stringify(feed).length;

        // DocumentDB has a response size limit of 1 MB.
        if (responseSize + queryPageSize < 1024 * 1024) {
          // Append query results to responseBody.
          responseBody = responseBody.concat(feed);

          // Keep track of the response size.
          responseSize += queryPageSize;

          if (responseOptions.continuation) {
            // If there is a continuation token... Run the query again to get the next page of results
            lastContinuationToken = responseOptions.continuation;
            tryQuery(responseOptions.continuation);
          } else {
            // If there is no continutation token, we are done. Return the response.
            __.response.setBody({
              "message": "Query completed succesfully.",
              "queryResponse": responseBody
            });
          }
        } else {
          // If the response size limit reached; run the script again with the lastContinuationToken as a script parameter.
          __.response.setBody({
            "message": "Response size limit reached.",
            "lastContinuationToken": lastContinuationToken,
            "queryResponse": responseBody
          });
        }
      });

    if (!accepted) {
      // If the execution limit reached; run the script again with the lastContinuationToken as a script parameter.
      __.response.setBody({
        "message": "Execution limit reached.",
        "lastContinuationToken": lastContinuationToken,
        "queryResponse": responseBody
      });
    }
  }
}
```

**Comment by lith-light-g** [comment]
I forgot about `IN`. Seems like I should use that instead.

I supposed if we have `pageSize = 100` we should be able to get up to 100 documents (in the feed response).
I initially didn't check if I had a continuation token and I actually had a continuation token that allowed me to get the desired document.
After further digging I noticed that this happens when I work with **arrays**.

Consider the following collection:
![collection](http://i.imgur.com/VK1QIOO.png)

```javascript
    var ids = ["471962d3-a021-4c12-86c9-01cca307b2a2", "d8f2966d-d1ea-4fef-8c1f-03b14678b5fd", "50d0ec4f-1c80-4ac8-a43a-fdfd62823414"];
    __.filter(function (i) {
        return i.id == ids[0];
    }, { pageSize: 1 }, function (err, feed, options) {
        __.response.setBody(feed);
    });
```
I initially thought this would get me the document whose id was 471962d3-a021-4c12-86c9-01cca307b2a2 but it didn't.
I got no result but I got a continuation token.

```javascript
    var ids = ["471962d3-a021-4c12-86c9-01cca307b2a2", "d8f2966d-d1ea-4fef-8c1f-03b14678b5fd", "50d0ec4f-1c80-4ac8-a43a-fdfd62823414"];
    __.filter(function (i) {
        return i.id == ids[0];
    }, { pageSize: 1 }, function (err, feed, options) {
        __.filter(function (i) {
            return i.id == ids[0];
        }, { pageSize: 1, continuation: options.continuation }, function (err, feed, options) {
            __.response.setBody(feed);
        });
    });
```
However, doing this gets the document (I suppose it's because it's the 2nd item in the collection).

```javascript
    var ids = ["471962d3-a021-4c12-86c9-01cca307b2a2", "d8f2966d-d1ea-4fef-8c1f-03b14678b5fd", "50d0ec4f-1c80-4ac8-a43a-fdfd62823414"];
    var id = ids[0];
    __.filter(function (i) {
        return i.id == id;
    }, { pageSize: 1 }, function (err, feed, options) {
        __.response.setBody(feed);
    });
```
If I'm not using an **array** I'm getting the document.

```javascript
    var ids = ["471962d3-a021-4c12-86c9-01cca307b2a2", "d8f2966d-d1ea-4fef-8c1f-03b14678b5fd", "50d0ec4f-1c80-4ac8-a43a-fdfd62823414"];
    __.filter(function (i) {
        return i.id == ids[0];
    }, { pageSize: 5 }, function (err, feed, options) {
        __.response.setBody(feed);
    });
```
Increasing the `pageSize` allows me to get the document.

The same behaviour is expected when using `indexOf()`.
I believe the scanning that you mentionned happens as soon as an array is involved.

This is crazy and I'm currently questionning my sanity :sweat_smile: 
But now I understand what's going on with `indexOf()` thanks !
