### ISSUE TITLE
id links

### ISSUE THREAD

**Issue by kspearrin** [Azure/azure-documentdb-js-server#2]
As mentioned in this [article](https://azure.microsoft.com/en-us/blog/azure-documentdb-bids-fond-farewell-to-self-links/), Is it possible to reference a document via it's id link rather than self link? It's pretty annoying and not very efficient to have to query for the document first every time.

For example, something like:
`collection.replaceDocument("/dbs/db_id/colls/coll_id/docs/doc_id", doc, callback);`

instead of:
`collection.replaceDocument(retrievedDocs[0]._self, doc, callback);`

If so, how do I resolve the collection link id from `getContext().getCollection()`?

Since we are performing this operation on a `collection` object already, it would be ideal if we could do something like:

`collection.replaceDocument("doc_id", doc, callback);`

**Comment by ryancrawcour** [comment]
that would be a great change, I have added the request to the backlog. 

for now, you can access the document directly using a link made up of the ids as per your example. the format for the document link is "dbs/<your db id>/colls/<your coll id>/docs/<your doc id>"

**Comment by kspearrin** [comment]
Good to know. The problem with the existing method is I don't know how to resolve the db id or coll id from `getContext()` to build the string. Is this possible today without having to pass that information in to the sproc via parameters?

**Comment by ryancrawcour** [comment]
you should be able to do getContext().getCollection().getAltLink(); ... this will give you the id based link for that collection. so something like "dbs/mydbid/colls/mycollid" then, you can append "/docs/mydocid" on to the end of that for the full path to the document.

**Comment by kspearrin** [comment]
Awesome. That should solve my problem them. Thanks!
