### ISSUE TITLE
upsert examples using unnecessary queryDocuments() call? 

### ISSUE THREAD

**Issue by dmeatte** [Azure/azure-documentdb-js-server#3]
[upsert.js](https://github.com/Azure/azure-documentdb-js-server/blob/master/samples/stored-procedures/upsert.js) and [upsertOptimizedForReplace.js](https://github.com/Azure/azure-documentdb-js-server/blob/master/samples/stored-procedures/upsertOptimizedForReplace.js) both use queryDocuments() to get the _self field to update a document. It looks like the 2015-08-06 release added the ability to [address documents using the id column](https://azure.microsoft.com/en-us/blog/azure-documentdb-bids-fond-farewell-to-self-links/). Are the calls to queryDocuments() still needed or can they be replaced with some string concatenation? Thanks.

**Comment by ryancrawcour** [comment]
this is correct. you no longer need to get the _self any more. you are able to address resources directly using links comprised of the actual ids. 

upsert and upsertOptimizedForReplace are no longer needed as we have Upsert functionality as a native feature in DocumentDB - https://azure.microsoft.com/en-us/blog/documentdb-adds-upsert/
