### ISSUE TITLE
When will these these stored procedures be updated to support partitioned collections?

### ISSUE THREAD

**Issue by stackoverflower** [Azure/azure-documentdb-js-server#4]
Do you plan to update these stored procedures to support partitioned collections anytime soon?

**Comment by arramac** [comment]
@stackoverflower stored procedures are already supported for partitioned collections. There are no changes in the programming API. 

However the execution semantics are different. Stored procedures for partitioned collections must include a partition key and are scoped to the transaction boundary of a single partition key value.

**Comment by steve-torchia** [comment]
@arramac can you show an example of how to include the partition key in the bulkdelete.js sample?

**Comment by diaconesq** [comment]
https://stackoverflow.com/questions/42299815/saving-testing-stored-procedures-triggers-maybe-user-defined-functions-for-p

**Comment by arramac** [comment]
+1 to @steve-torchia. BTW, the issue of upserting the SP itself has also been fixed. Closing this issue.

**Comment by diaconesq** [comment]
I just hit the 'upsert SP on partitioned collection' issue today.
I would expect the fix to be server-side, right?

**Comment by eladkamin** [comment]
I just got the 'Upserts for scripts in collections with multiple partitions are not supported' error today.
When will upsert stored procedures will be updated to support partitioned collections?

**Comment by chlahav** [comment]
@eladkamin I had the same issue, using the ReplaceStoredProcedureAsync function as described in the stackoverflow thread from above worked perfectly for me

```csharp
try 
{
    await _client.CreateStoredProcedureAsync(...);
} 
catch(DocumentClientException dex) when (dex.StatusCode == HttpStatusCode.Conflict) 
{ 
    await _client.ReplaceStoredProcedureAsync(...);  
} 
```
