### ISSUE TITLE
Is it "QueryResponse.isAllowed" or "Query.isAccepted" ?

### ISSUE THREAD

**Issue by mdufourneaud-m2ocity** [Azure/azure-documentdb-js-server#6]
There is a mismatch between the documentation of the "DocumentDB server side JavaScript SDK" that indicates `QueryResponse.isAllowed` (cf. https://azure.github.io/azure-documentdb-js-server/D__DocDbWrapperScript.js.html#line1788), and the object returns by a `Collection.value()` call that is implemented as `QueryResponse.isAccepted`.

**Comment by emilylawton** [comment]
Thanks for bringing this to our attention, @mdufourneaud-m2ocity. This is a mistake in the documentation of the wrapper script. We will update this, changing `QueryResponse.isAllowed` to `QueryResponse.isAccepted`.
